### ISSUE TITLE
Naive AutoML can get stuck in infinite loop if no working pipeline is found

### ISSUE THREAD

**Issue by PGijsbers** [fmohr/naiveautoml#26]
This piece of code is supposed to try and salvage a pipeline as a last resort:
https://github.com/fmohr/naiveautoml/blob/603927acee5454b7fce2ef8ba0f3e8eaa68614ce/python/naiveautoml/naiveautoml.py#L443-L450

However, since slicing an empty list as `[][1:]` is legal and produces an empty list `[]`, when there are no more steps in the pipeline, there is no longer a way to break out of the loop:
 - `fit` fails
 - the pipeline is shrunk to the same empty-list pipeline

**Comment by fmohr** [comment]
@PGijsbers, let's track this down. It must actually not happen, because it means that the classifier alone throws an exception (but if this happened, it would not have been selected in phase 1). Can you provide the dataset on which it happens?

**Comment by PGijsbers** [comment]
I sent messages on Slack. If need be, I can see if I can get more information from the amlb logs next week.

**Comment by fmohr** [comment]
Hey @PGijsbers, I lost a bit track on this issue and could not find anything on this in our slack history. Do you think that this is still an issue?

**Comment by PGijsbers** [comment]
Yes, [the code is still there](https://github.com/fmohr/naiveautoml/blob/f9b89374f2924ce6eece0f7658f6358afd6b4db4/python/naiveautoml/naiveautoml.py#L513-L520). If, for whatever reason, it reaches that part and the classifier/regressor can not fit, then the loop will run indefinitely. At the very least, it should check that `self.pl.steps[1:]` does not result in an empty list, if it does, it also has to break out of the loop (and raise some error that no pipeline was found, or do some other kind of back up). I responded to the relevant thread in slack so that you can find it.

**Comment by fmohr** [comment]
I think the problem should be fixed now.
